- build.gradle.kts
Upgrade log4j version to 2.17.1 for gradle build
> vb-438 log4j CVE-2021-45105

- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/health/InfoTest.kt
DPS gradle plugin upgrade for combined fix:
- CVE-2021-44832
- CVE-2021-45105
- CVE-2021-42550
> DPS Gradle upgrade to 4.0.1

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/VisitScheduler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/filter/VisitFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/specification/VisitSpecification.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/main/resources/db/migration/V1_0__create_tables.sql
- src/test/resources/application-test.yml
- src/test/resources/migration/drop_tables.sql
VB-450 Reserve Visit Slot - Expired edge case.
Scheduled Task created to delete expired reservations if not modified within validity period.
Configurable cron and validity period added to application properties.
> vb-450 expired reserved visit scheduled task

- src/main/resources/application-dev.yml
Increases the Prison API timeout in DEV
Set a realistic timeout for the environment.
> Prison API DEV timeout

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/ContactDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateContactOnVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitorOnVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/UpdateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitSession.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitorDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt
- src/main/resources/db/migration/V1_1__main_contact_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/VisitRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitSessionsResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerServiceTest.kt
Add a main contact association to a visit 
Allows the update of a visit main contact name and telephone number which may not be a registered prisoner contact.
- New contact table
- Put visit endpoint
- Entity, DTO & swagger update
- Additional tests
> VB-528 Main Contact Person

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/UpdateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt
- src/main/resources/db/migration/V1_2__add_visitor_concerns_column.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerServiceTest.kt
Adds the visitor concerns column to the visit table
Provide a field to store visitor concerns when migrating visit data.
> VB-521 Visit Visitor Concerns text

- .circleci/config.yml
Disables Circle CI PROD deployment
> vb-583 disable prod deployment

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/VisitScheduler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/ContactDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitorDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitStatus.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitVisitor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/generator/ReferenceIdGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoder.kt
- src/main/resources/application.yml
- src/main/resources/db/migration/V1_0__create_tables.sql
- src/main/resources/db/migration/V1_1__main_contact_table.sql
- src/main/resources/db/migration/V1_2__add_visitor_concerns_column.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/VisitRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoderTest.kt
- src/test/resources/migration/drop_tables.sql
Replaces the Visit resource id with a custom generated reference.
Removes redundant visit columns
Removed redundant visit ids
Minor clean up
To provide the UI with the requested readable visit reference as the visit id which matches the formatting requirements, excludes common curse words, cannot be easily guessed, does not cause collision, and is fast.
> Vb 403 visit ref

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/AvailableSupport.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/SessionException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/SessionTemplate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Support.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/SupportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitSupportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt
- src/main/resources/db/migration/V1_1__create_support_table.sql
- src/main/resources/db/migration/data/R__add_support.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitSupportResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerServiceTest.kt
Adds the ability to request a list of available support.
To provide the UI with a list of additional support available for a visit booking.
> Vb 582 support

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoderTest.kt
> vb-403 exclude chars

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/VisitSchedulerExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateSupportOnVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/SupportDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/UpdateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/SessionException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/SessionTemplate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Support.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitSupport.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitVisitor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/SupportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
- src/main/resources/application-dev.yml
- src/main/resources/db/migration/V1_2__create_visit_support_table.sql
- src/main/resources/db/migration/V1_3__drop_adjustments_column.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerServiceTest.kt
- src/test/resources/migration/drop_tables.sql
Replaces the visit free text Reasonable Adjustments column with a list of available Support.
To all the UI to record multiple support requirements (Pre-defined & free text) against a visit.
> VB-330 Additional visit support

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitSupport.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitVisitor.kt
Prevents stack overflow in equals, hash & toString
> re-implement equals hash toString

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitNoteType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitNotes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt
- src/main/resources/db/migration/V1_0__create_visit_table.sql
- src/main/resources/db/migration/V1_7__create_visit_notes_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerServiceTest.kt
refactor visitor concerns into a generic table
to improve db relationship and to prevent duplication
> VB-614 Refine visitor concerns

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/UpdateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitNoteDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitNote.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitNoteType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
Add's visit outcomes to the visit notes
allow legacy visit outcomes to be added to the new system
> VB-615 Visit Outcomes

- .trivyignore
- build.gradle.kts
> Upgrade to 4.1.2

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitNoteType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
Allows visit comment to be added to via visit Notes 
To bring in visit notes from the legacy system
> VB-554 Comment Text attribute for a visit entry

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/ContactDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateContactOnVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateSessionTemplateRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateSupportOnVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitorOnVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/UpdateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitorDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitorSupportDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
Removes the ability to amend notes - covered by vb-600
Clean up code format
Prevent data loss from nomis migration prior to vb-600 feature.
> Amend visit notes removed

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitNote.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitNoteType.kt
- src/main/resources/db/migration/V1_7__create_visit_notes_table.sql
Allows legacy status change reasons to be stored in a generic way in new system
To store legacy data in the new system without impacting the new system with legacy structures
> VB-612 Refine Visit Reason status for legacy

- src/main/resources/db/migration/V1_1__create_visit_visitor_table.sql
- src/main/resources/db/migration/V1_5__create_visit_support_table.sql
- src/main/resources/db/migration/V1_6__create_visit_notes_table.sql
added index on one to many relationships 
make sure, basic indexing is in place for performance reason
> VB-629 Create Index of vistit_ID on sub tables

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitStatus.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitSessionsResourceIntTest.kt
remove unwanted status types
to remove unwanted code
> VB-635 Remove sub status types from VisitStatus

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateLegacyDataRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/LegacyData.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/LegacyDataRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/resources/db/migration/V1_7__create_legacy_data_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt
allows us to have a lead visitor legacy data from nomis with minimal pollution of new system
Make sure the new system is clean of legacy issues and data structures
> VB-613 Refine lead visitor

- Dockerfile
- README.md
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Resolves 5 (2 docker, 3 Jar) CRITICAL trivy scan security failures in build
Prep for promoting into pre-prod
> VB-616 Build config

- build.gradle.kts
- docker-compose-localstack.yml
- helm_deploy/visit-scheduler/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SnsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/resources/application-localstack.yml
Sends a  prison-visit.booked event to the domainevents topic for testing the DEV env configuration
To test SNS events in the DEV environment.
Note: 
This branch is for testing WIP and requires localstack tests and refinement.
> Initial SNS Service with book a visit event trigger

- build.gradle.kts
Upgrade to gradle plugin 4.1.4 for build warnings
> Upgrade gradle plugin

- .circleci/config.yml
removed invalid config from circle config.yml
> Circle config clean up

- build.gradle.kts
> Redundant dep removed

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitNoteDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitControllerTest.kt
Allows the all notes details to be returned
to allow the ui to display all the information for the ticket
> VB-679 Return required information for migrated and non-migrated data

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitControllerTest.kt
Adds a cancel visit endpoint to the visit controller
Allow the client to cancel a visit
> VB-643 Cancel endpoint added to visit resource

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitControllerTest.kt
Adds the visit created timestamp to the get visit response
Allows the client to identify when a visit was originally created
> VB-660 Created timestamp added to visit response

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateSessionTemplateRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateVisitRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/OutcomeDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/OutcomeType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/CancelVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitControllerTest.kt
The user can now store a reason and bespoke text against the canceled visit
To allow MOJ to monitor why visits are canceled
> VB-667 Store the reason

- .circleci/config.yml
- helm_deploy/values-staging.yaml
Add CICD values for staging environment
create microservices in new namespace
> Add CICD values for staging environment

- .circleci/config.yml
- helm_deploy/values-staging.yaml
Add CICD for staging environment
enable this repo to be pushed into VSIP-dev namespace
Final commit - chose blue for context colour - should have been green -  now changed
> Add CICD for staging environment

- .circleci/config.yml
- helm_deploy/values-staging.yaml
Change context from blue to green_
Satisfy CP requirements
> https_/dsdmoj.atlassian.net/browse/VB-686_-_add_CICD_config_for_staging_env

- build.gradle.kts
Upgrade dependencies
Resolve build security warnings
> VB-666 Upgrade to 4.1.5

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/SendDomainEventTest.kt
Restricts create and update domain events to BOOKED status pending VB-501
Prevent undesired domain events on create and update.
> VB-638 Check for status Booked added until VB-501

- .circleci/config.yml
remove approval requirement for deployment to staging env
remove manual step
> Remove_approval_requirement_for_staging_environment

- build.gradle.kts
- docker-compose-localstack.yml
Upgrades the dps gradle plugin to version 4.1.6
resolves trivy warnings in the build
> VB-730 upgrade dps plugin to 4.1.6

- helm_deploy/visit-scheduler/values.yaml
Adds namespace secrets to helm config for 'domainevents' topic
> vb-638 domainevents helm config

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Revise subdomain name
Conform to HMPPS Guidelines
Note : this will break affected environments - need to co-ordinate a number of PR merges to minimise downtime
> https_/dsdmoj.atlassian.net/browse/VB-775

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/CreateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/SendDomainEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/UpdateVisitTest.kt
It fixes a task that was not needed
Complies with restful convention
> VB-795 Need RESTful responses from visit create/update

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/OpenApiConfiguration.kt
Revise subdomain in openAPI configuration
make openAPI correct
> https_/dsdmoj.atlassian.net/browse/VB-787_Pt2

- .circleci/config.yml
enable deployment to production environment
Commission production environment
> Commission production environment

- helm_deploy/values-prod.yaml
Add prod environment contect colour - green
Satisfy CICD requirement for a context colour
> Commission prod environment - contexgt colour

- build.gradle.kts
Upgrade to dps gradle plugin and dependencies for version 4.1.7
Resolve build warnings
> VB-844 Upgrade dps plugin 4.1.7

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/LegacyData.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/resources/db.scripts/test/VB-831_clear_all_variable_visit_data.sql
- src/main/resources/db.scripts/test/VB-831_remove_all_migrated_visit_data.sql
- src/main/resources/db/migration/V1_9__remove_legacy_data_constraint_from_legacy_data_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/MigrateVisitTest.kt
Added test sql scripts to remove migrated data and another script to remove variable visit data
To improve testing efficiency and accuracy
> VB-831 Facility to clear test data from given system environment

- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Improves test coverage for Session templates
proves if concept works, reduces bugs
> Improved test coverage for sessions templates

- build.gradle.kts
Gradle plugin upgrade to version 4.2.1
> VB-913 Gradle plugin upgrade to version 4.2.1

- .circleci/config.yml
- build.gradle.kts
Upgrades dependencies
Upgrades dependencies
> Vb 916 gradle plugin

- build.gradle.kts
hmpps-sqs-spring-boot-starter to version 1.1.5
> VB-980 Upgrade sqs to version 1.1.5

- build.gradle.kts
Upgrade to gradle plugin version 4.3.2
Resolve build security warnings
> VB-1028 Upgrade to version 4.3.2

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateSessionTemplateRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/SessionTemplate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/resources/db.scripts.mvp/R__VB-819_add_hewell_code_HEI_prison_data.sql
- src/main/resources/db/migration/V2_02__session_template_table_rename_expiry_and_start_columns.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitSessionTemplateControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitSessionsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
aligned implementation to story terms 
to enabled constant naming, to improve readability and maintainability
> VB-992 Create visits schedule - Validity period

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateLegacyContactOnVisitRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/MigrateVisitTest.kt
Capitalise legacy contact data
Sanitises migrated data via API for defect VB-932
> VB-932 Capitalise legacy contact name

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/VisitSchedulerExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitSessionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/SessionConflict.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
- src/test/resources/application-test.yml
Adds additional information to the available sessions response.
Adds conflict filtering configuration to the application config.
Provide the client with additional information about the available sessions.
> VB-717 Conflicts added to available sessions response

- build.gradle.kts
update dps plugin to 4.4.1
keep things up to date
> upgrade-dependancies-from-4.3.3

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/validators/VisitorContactValidator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/validators/VisitorValidator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateVisitRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/UpdateVisitRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitorDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/VisitVisitor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SupportTypeRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/resources/db/migration/V2_03__add_visit_contact_to_visitors.sql
- src/main/resources/message.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/CreateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/DeleteVisitByReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/MigrateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/SendDomainEventDisabledTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/SendDomainEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/UpdateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitsByFilterTest.kt
Connects the visit contact to the visitors list
to make sure the data is rationalised
> VB-1104 Connect visit contact to visitor list

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
- helm_deploy/visit-scheduler/Chart.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/ResourceServerConfiguration.kt
it updated to latest plugins and dependencies
to ensure security of code is up to-date,
> VB-1124 Update plugins and dependencies

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
- src/test/resources/application-test.yml
attempts to fix timeout by reducing calls to DB with checking non-association with visits
to fix the bug
> VB-1140 Visit scheduler timing out

- src/main/resources/db.scripts.mvp/R__VB-819_add_hewell_code_HEI_prison_data.sql
corrects a case issue with the main room name from **visits main room** to **Visits Main Room**
to match VSiP with other services
> VB-1157-Defect---correct-R__VB-819_add_hewell_code_HEI_prison_data.sql

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/BookedVisitByReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitByReferenceTest.kt
fixes bug desribed in VB-1166
To fix the bug
> VB-1168 Add new get end point /visits/booked/{reference}

- build.gradle.kts
update to gradle-spring-boot to version 4.5.0
to keep project up to date with latest dependencies
> VB-1183-Update-Dependencies-VSiP

- src/main/resources/db.scripts.mvp/R__VB-819_add_hewell_code_HEI_prison_data.sql
Last minute session template changes
To ensure the HEI is configured properly
> VB-1187 Last minute session template changes

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Make only 1 call to prison API to get the offender's list for a prisonerId. Currently the calls are being multiple times i.e. for each session.
Performance improvements and reduced downstream calls.
WIP change only, not to be merged now.
> Vb 1197 WIP - reduce number of calls to prison api in get visit sessions

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/projections/VisitRestrictionStats.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/container/TestVisitRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/CleanUpVisitsScheduleTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
- src/test/resources/application-test.yml
This update the repository sql and Schedule task to use latest approach to Visits Reference
Yo match the SQLs to the code base to allow one reference across multiple visits
> VB-1207 Update database calls to use the latest reserved bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/MigrateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitByReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/legacy/UpdateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/CleanUpVisitsScheduleTest.kt
Basically more than one visit was being return in a DB call that only expected one. now we return the latest BOOKED or CANCELED visit
to fix bug
> VB-1249 500 error on GET /visits/{reference}

- .trivyignore
- build.gradle.kts
It updates the dependencies to latest versions
to improve security and reduce bugs
> VB-1309 VSiP Update dependencies

- .circleci/config.yml
Added a new job for tests against the main branch to run on a daily basis. 
Updates to add a new cron job and updates to slack channel.
> VB-1340 daily test run on main branch

- .circleci/config.yml
- helm_deploy/values-staging.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/OpenApiConfiguration.kt
VSiP change for staging env
to allow us to have a staging environment
> VB 1351 Create values staging and add staging details to CI config

- build.gradle.kts
Update to dependancies
Makes sure our 3rd party dependencies have latest fixes
> VB-1363 VSiP Update dependancies

- build.gradle.kts
Update hmpps.gradle-spring-boot dependency to 4.5.7
Fixes for security issues.
> Update hmpps.gradle-spring-boot dependency to 4.5.7

- src/main/resources/db/migration/data/R__add_prison_codes.sql
add's permitted prison codes, if already thire it ignores. 
To add BRS prison to allow testing of new prison switcher
> VB-1431 Add new prison codes to DB

- build.gradle.kts
Have to add this to prevent the following errors in "Execution failed for task ':bootJarMainClassName'.
> Unable to find a single main class"
_Required._
_Required._
> Explicitly name spring boot application to prevent error

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/legacy/CancelVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
Additional data sent to application insights.
To allow better reporting on app insights.
> VB-1436 send more data to app insights to allow better reporting.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionTemplate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtil.kt
- src/main/resources/db/migration/V2_11__add_bi_weekly_to_session_template_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/PrisonerSessionValidatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtilTest.kt
Adds bi-weekly functionality
allow configurations for bristol
> VB-1434 Add code to server side to allow for bi-weekly session templates

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionTemplateSQLGeneratorApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/SessionTemplateSQLGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtilTest.kt
adds validation for CSV files
to reduce risk of system template data being incorrectly configured
> Improvement to sql generator, added validation

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionTemplateSQLGeneratorApplication.kt
- src/main/resources/session-template-data/template.ftl
removes SQL in code and put's it into a free marker template
To separate code from output to follow POC
> Improvement to sql generator, to use freemarker template

- .trivyignore
- build.gradle.kts
Updated Dependency code to latest versions
for security and defect fixes
> VB-1471 OWASP Dependency-Check Analyzer - failed

- src/main/resources/db.scripts.mvp/fix_up_visits_with_wrong_times_new_code_base.sql
- src/main/resources/db.scripts.mvp/fix_up_visits_with_wrong_times_old_code_base.sql
Added a script to alter times of Xmas period,..
To fix timetable to xmas time table
> VB-1487 Update visits for xmas script

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitControllerLegacy.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/VisitFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/specification/VisitSpecification.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByFilterTest.kt
adds functionality to search on more than one status
to apply requirements in stories and from user research
> VB-1451 Extend service to allow 'cancel' and 'booked' filtered visits

- .circleci/config.yml
Created a flow for Circle CI develop flow
to allow us to work on different streams of work,... live defects / updates to dependancies and sprit work at the same time
> Circle Ci Develop flow

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/resources/db/migration/V2_13__add_index_to_prison_ids.sql
Reduces duplicate class to DB in regards to no association sessions
to improve performance
> VB-1501 Performance improvements

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/LegacyData.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Prison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/SupportType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/VisitContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/VisitNote.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/VisitSupport.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/VisitVisitor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/PermittedSessionLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionTemplate.kt
change all entities from data classes to open classes as pr JPA recommendations.
performance improvements and to follow recommendations.
> VB-1486 - change all entities from data classes to open classes

- build.gradle.kts
Update to hmpps.gradle-spring-boot dependency.
Periodic version updates as security fixes.
> Update hmpps.gradle-spring-boot dependency to latest version (4.7.4)

- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtilTest.kt
Fixes up the tests for Sunday run, code was added at some point that adjusts the the bi weekly to start of week when this was done these test started failing
To make sure test work correctly on a Sunday...
> VB-1532 Fix bi weekly Sunday test fail

- src/main/resources/db.scripts.mvp/fix_up_past_visits_for_bristol_on_december_31st.sql
Changes some past visits to correct date and times
to fix up errors from migrated and created bookings..
> VB-1563 Update HMP Bristol visits for 31/12/22

- .trivyignore
- build.gradle.kts
Updates hmpps-gradle dependency to 4.8.1 and other minor dependency updates
To upgrade to latest build as a fix for security issues.
> VB-1688 Update hmpps-gradle dependency to 4.8.1 and other minor dependency updates

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionTemplate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/resources/application.yml
- src/main/resources/db/migration/V2_15__add_enhanced_prisoner_to_session_template.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonOffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Code to allow incentive logic and db entities and 
to for-fill  Vb 1699
> Vb 1699 implement the v si p code to store incentive information and process it

- src/main/resources/db.scripts.mvp/delete_specific_future_dated_visits.sql
Deletes 5 specific future dated visits.
Prison specific request.
> VB-1766 - delete 5 future dated visits.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitControllerLegacy.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByFilterTest.kt
Removed legacy end point that is no longer used
remove unused code to improve maintainability
> Vb 1800 remove legacy visit end point

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
To prevent multiple requests being process when booking and cancellation of visits
to improve data quality
> Vb 1732 duplicate booking and cancellation requests being fired

- src/main/resources/db.scripts.mvp/delete_duplicate_booking.sql
deletes a duplicate booking
removed unwanted data and unwanted bookings
> Vb 1814 delete duplicate booking in production database

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/OpenApiConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/CreateSessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionScheduleTest.kt
Change some api params for session schedule endpoint and description was incorrect
to improve code quality and to remove incorrect description text for api
> Change some api params for session schedule endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionScheduleTest.kt
Returns Enhanced in prison schedule
to allow the UI to display the correct data to the user
> VB-1878 Server side to return Enhanced in DTO

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
Updates code to allow cancellation of cancelled visits.
Fix for VB-1981.
> VB-1981 - updates to allow updated visits to be cancelled.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/CreateSessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt
Adds element to UI for prisoner Categories, but dummies data
to allow other services to update there code without waiting for server side dev
> Vb 2002 admin api tasks server side dummy request response m

- Dockerfile
- gradlew
- gradlew.bat
What does this pull request do?
makes sure code is compiled to the correct version of the JDK
What is the intent behind these changes?
to get CI build working
> VB-2005 Update VSiP Dependencies - change to CI JDK version attempt 4

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/PrisonerOffenderSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonerDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prison/api/PrisonerDetailsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prisonersearch/PrisonerSearchResultDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionPrisonerCategory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionTemplate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionPrisonerCategoryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/resources/db/migration/V2_19__add_prisoner_category.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonOffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/CreateSessionsTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithLevelsHousingLocationMatcherTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/UpdateSessionsTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Allow the session to be selected using the prisoner category
Allow the session to be selected using the prisoner category
> Vb 2000 server side logic for inclusive/exclusive category

- Dockerfile
- applicationinsights.dev.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/MigrateVisitRequestDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/MigrateVisitTest.kt
small change in develop that needed to be merged into main
so we can release with features covered in sprint
> Merge develop into main

- .circleci/config.yml
Update validate to large resource class in config.yml as suggested by CircleCI
Circle CI suggestion for memory issues
> Update validate to large resource class in config.yml

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/TransitionalLocationTypes.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/TransitionalLocationTypesTest.kt
It makes sure it's check for temp location ignores case, also adds further tests
to make code stable
> VB-2041 Update to TransitionalLocations check

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/PrisonApiClient.kt
removed code that had no function
to clean up code base
> VB-2041 Removed code that was not needed

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/PrisonApiClient.kt
Merges changes from main into develop
> VB-2041 Removed code that was not needed (#323)

- applicationinsights.json
- src/main/resources/logback-spring.xml
update to logback-spring to remove logappender and updates to applicationinsights.json.
Updates to logback-spring to reduce logging
Reduce logging on preprod and prod
> VB-2096 - update to logback-spring and applicationinsights.json

- applicationinsights.json
- src/main/resources/db.scripts.mvp/update_visit_timings_bullingdon.sql
- src/main/resources/logback-spring.xml
update develop branch with main changes
update develop branch with main changes
> Merge main to develop

- src/main/resources/db.scripts.mvp/switch_on_on_board_prisons.sql
- src/main/resources/db/migration/data/R__add_prison_codes.sql
adds new prison to prison table and another script to enable them
to onboard new prisons
> Sql scripts to add prisons and turn them on when neeeded

- helm_deploy/visit-scheduler/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/WebClientConfiguration.kt
- src/main/resources/application.yml
Connects using client id
2nd attempt after adding properties to values.yaml
> Connect using clientid 2

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/resources/db/migration/V2_21__update_action_by_for_legacy_data.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitTest.kt
remove client Id from DB and also set data to create by and canceled by to NOT_KNOWN_NOMIS id client Id used
to make sure information is useful to user.
> Vb 2105 migrated data showing incorrect booker information

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
adds extra logs for category 
to help support and testing
> Improve logs for prisoner cat

- .circleci/config.yml
Added pre-prod release ability for develop branch
> Added preprod for develop branch

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitSessionMatchTest.kt
improve logging to help migration of data and detection of detects
improve migration capacity counts with in 28 days
> Improved logs to help testing and support

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitSessionMatchTest.kt
to improve logs to assist support and testing
> Improved log message v2

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt
Improves logs so we can track migrated data by room name
> Improved logs for migration

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt
corrected a small error in logs
> Added new logs to help test when a prisoner is moved, error in logs

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt
Added some extra logs to help test
> Added some extra logs, to help test

- src/main/resources/db/migration/V2_25__add_migration_date.sql
Added migration date and time to help in recovery of failed migration to default to null
> Added migration date and time to help in recovery of failed migrations.

- src/main/resources/db.scripts.mvp/update_durham_session_templates.sql
update Durham session templates to match current prison timetable.
updates to Durham timetable to match Live.
updates to Durham timetable.
> VB-2247 - update Durham session templates

- src/main/resources/application.yml
temporary update to run flag visits task at 15:40.
temporary update to run flag visits task at 15:40.
> update scheduled time to run task at 15:40.

- src/main/resources/application.yml
reverts scheduled time to run flag visits task at 3 AM.
reverts scheduled time to run flag visits task at 3 AM.
> revert scheduled time to run flag visits task at 3 AM.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/PrisonConfigController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Prison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/PrisonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/resources/messages.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/config/GetPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
add's activate, deactivate and create and get all prisons
to allow the admin api to manage prisons online
> Prison admin api, for get all prison, active deactivate, and create

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/PrisonConfigController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Prison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/PrisonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
- src/main/resources/application.yml
- src/main/resources/db.scripts.mvp/VB-2249_Script_to_detect_mismatched_session_to_visits_dmi.sql
- src/main/resources/messages.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/config/GetPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitSessionMatchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
> Merge main into dev

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prison/api/PrisonerHousingLocationsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrationIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithLocationsWhenPrisonerIsTransitionalTest.kt
This PR switches from our temporary solution used before syscon had implemented theres 
Our approach only works with certain prisons, syscon should work on all prisons, plus this is the correct service to have it in.
> VB-2097 Use new Syscon endpoint for housing location

- src/main/resources/db.scripts.mvp/update_bristol_visits_session_template_reference_week2.sql
Updates end_time to visit_end on week 2 queries.
Updates end_time to visit_end on week 2 queries.
> update end_time to visit_end.

- src/main/resources/db.scripts.mvp/VB_2274_exclude_durham_22_Jun.sql
Fix for VB-2274, exclude 22nd June timetable for Durham.
Timetable update for Durham
> VB-2274 - exclude 22nd June timetable for Durham.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionScheduleTest.kt
A fix to ensure schedule in correct time order
to improve customer exsperiance
> A fix to ensure schedule in correct time order

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/ScheduledCacheEvictTask.kt
Remove caching from admin API endpoints
> VB-2314 Remove caching from admin API endpoints

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/LocationGroupAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/PrisonConfigController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prison/api/PrisonerHousingLocationsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/PrisonExcludeDateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/resources/messages.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/config/GetPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrationIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonConfigTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/CreateSessionGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/CreateSessionsTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/DeleteSessionTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithLocationsWhenPrisonerIsTransitionalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/SessionGroupByLocationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/UpdateSessionLocationGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/UpdateSessionsTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoderTest.kt
> Merge develop into main v4

- src/main/resources/db.scripts.mvp/VB_2327_disable_bristol_monday_session_template.sql
Remove Monday sessions from Bristol timetable.
Remove Monday sessions from Bristol timetable.
> VB-2237 - remove Monday session template.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SnsService.kt
Added some extra logs to help us track the domain events
> VB-2332 Added additional information to logs

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionTemplateTest.kt
Changes session template end point to allow UI to select session templates by from and to date using a flag
> VB-2335 Create active in active get Session Template end point

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionTemplateTest.kt
Bug detect my tom change how the code worked.
> Vb 2335 create active in active get session template end point fix

- helm_deploy/values-dev.yaml
Update flag visits cron job timings on dev to run every hour.
Update flag visits cron job timings on dev to run every hour.
> Update dev flag visit timings

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitControllerLegacy.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitPrisonsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSupportController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/LocationGroupAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/SessionTemplateAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/migration/MigrateController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminCreateSessionTemplateGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminCreateSessionsTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminDeleteSessionTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminGetSessionTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminGetSessionsTemplateLocationsWhenPrisonerIsTransitionalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateLocationGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateLocationGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/GetVisitPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitSupportControllerTest.kt
Re factored end point's no functional change, also rename classes and moved to improved packages
> Vb 2341 move admin endpoints into correct code base/package

- src/main/resources/db/migration/V2_26__add_index_for_visit_reference.sql
Added missing index to speed up search on the DB
> Added Index for visit reference

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonerCategoryGroupsAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/category/CreateCategoryGroupDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/category/UpdateCategoryGroupDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionCategoryGroupRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminCreateSessionsTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateCategoryGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateLocationGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateLocationGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestSessionCategoryGroupRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestSessionCategoryRepository.kt
Add create update delete category for sessions
To allow us to updated these details via the admin system
> Add create update delete catigory for sessions

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonerCategoryGroupsAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonerIncentiveGroupsAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/SessionTemplateAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/migration/MigrateController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/incentive/CreateIncentiveGroupDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/incentive/SessionIncentiveLevelGroupDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/incentive/UpdateIncentiveGroupDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/incentive/SessionPrisonerIncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionIncentiveLevelGroupRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateIncentiveGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestSessionIncentiveLevelGroupRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestSessionPrisonerIncentiveLevelRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoderTest.kt
Build API Endpoints to enable maintenance of Incentive Level Groups
To allow us to on board and perform BAU tasks when needed
> Vb 2348 build api endpoints to enable maintenance of incentives

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/CreateSessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt
Update swagger docs for create and update session template dto.
Update swagger docs for create and update session template dto.
> VB-2223 - update swagger docs.

- src/main/resources/db/migration/data/R__add_prison_codes.sql
Remove dates from Foston Hall schedule in VSiP (FHI)
> VB-2377 Remove dates from Foston Hall schedule in VSiP (FHI)

- src/main/resources/db/migration/data/R__add_prison_codes.sql
VB-2388 Block date from Cardiff schedule in VSiP (CFI)
VB-2386 Block date from Durham schedule in VSiP (DMI)
> VB-2386 VB-2386 Block date from Durham & Cardiff schedule

- src/main/resources/db/migration/data/R__add_prison_codes.sql
VB-2399, block specific dates - HMP Durham
> VB-2400 HMP Durham - VSiP - Block specific dates

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonExcludeDateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
Refactor of exclude date, after review from @infojav
> Refactor of exclude date, after review from javier

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/SessionTemplateAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminDeleteSessionTemplateTest.kt
Updates to delete a session template.
Updates to delete a session template to return a JSON response and add check to see if the session template is active.
> VB-2362 - update delete to return a JSON response and check if session template is active.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/LocationGroupAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonerCategoryGroupsAdminController.kt
RequestBody for update and create location groups was incorrect and update on category
> Fix up create group dto endpoint

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Update dps gradle spring boot version to 5.2.2.
Security fixes.
> Update dps gradle spring boot version to 5.2.2.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionDateRangeDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTimeSlotDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
Adds validations around updates to session times and valid from date.
Admin API improvements.
> VB-2445 - Validations around session time and valid from updates.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/LocationGroupAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonerCategoryGroupsAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonerIncentiveGroupsAdminController.kt
Similar to https://github.com/ministryofjustice/visit-scheduler/pull/463
Return JSON when delete is successful
Copy the work done in the above mentioned PR for:
Incentive groups
Location groups
Category groups
> Admin controllers delete return

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
Add value to App Insights customEvent
> Vb 2349 add value to app insights custom event

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/ScheduledCacheEvictTask.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/GetVisitPrisonsTest.kt
- src/test/resources/application-test.yml
Revert back caching of supported prisons.
Admin API and general improvements.
> Vb 2462 revert back caching of supported prisons

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/SessionTemplateAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/RequestSessionTemplateVisitStatsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateVisitStatsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateVisitsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Add session template visit stats for admin
> Vb 2467 add session template visit stats for admin

- src/main/resources/db/migration/data/R__add_prison_codes_excl_dates.sql
[VB-2483](https://dsdmoj.atlassian.net/browse/VB-2483)
Block date from Preston (PNI) schedule in VSiP
[VB-2483]: https://dsdmoj.atlassian.net/browse/VB-2483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VB-2483 Block date from Preston (PNI) schedule in VSiP

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
Adds validations around updates to weekly frequency.
Admin API improvements.
> VB-2484 add validation around updates of weekly frequency

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryVisitEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/CleanUpVisitsScheduleTest.kt
Add customEvent to App Insights for when a reservation is released
> Vb 2315 add custom event to app insights for when a reservation is released

- src/main/resources/db/migration/V2_29__add_event_audit.sql
- src/main/resources/db/migration/data/R_remove_legacy_visits_that_are_six_months_in_future.sql
VB-2481 Delete visits in Live too far in the future
> VB-2481 Delete visits in Live too far in the future

- src/main/resources/db/migration/data/R__add_prison_codes_excl_dates.sql
VB-2546 Block date from Preston (PNI) schedule in VSiP
> VB-2546 Block date from Preston (PNI) schedule in VSiP

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/audit/EventAuditDto.kt
Create timestamp not updating from db for events audit
> VB-2550  Create timestamp not updating from db for events audit

- build.gradle.kts
Updates dependencies for security failures.
Fix for security failures.
> Update dependencies for security failures.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/VisitSchedulerExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/exception/VSiPValidationException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/UpdateSessionTemplateValidator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminDeleteSessionTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateCategoryGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateIncentiveGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateLocationGroupTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
Adds validation updates around session capacity and allows multiple validation errors.
Admin API improvements
> VB-2562 - validation updates around session capacity and updated VSiPValidationException to include multiple error messages.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/CreateSessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt
weeklyFrequency on UpdateSessionTemplateDto should be optional
weeklyFrequency on CreateSessionTemplateDto should be required
> weeklyFrequency change

- src/main/resources/db.scripts/test/R__VB-831_remove_EEI_migrated_data_for_2023-07-25T21-58-41.sql
Migration Id: 2023-07-25T21:58:41
Status: COMPLETED
Started: 25 July 2023 - 21:58 Ended: 25 July 2023 - 21:59 Migrated: 1315 Failed: 0 Estimated: 1315
Migration properties:
Prisons:EEI
Visit types:SCON
From date:30 April 2023 - 00:00
> Remove EEI migrated data for :

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/EventAuditType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/AssertHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitHistoryByReferenceTest.kt
Fix to sort out spelling error in server side
> Fix for cancel error

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/EventAuditRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrationIntegrationTestBase.kt
Fixes a bug described in Vb 2592
> Vb 2592 calculate the cost of our service migration event date is not migrating properly

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/EventAuditType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/AssertHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitHistoryByReferenceTest.kt
> Fixed up merge issue

- src/main/resources/db/migration/V2_30__add_event_audit_for_migrated_canceled_visits.sql
Update to script to allow for cancel migrated visits
> Udapte to script to allow for cancel migrated visits

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/SessionTemplateAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/SessionDetailsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionDetailsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtil.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionTemplateComparator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionTemplateMapper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminCheckMatchingTemplatesOnCreateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminCheckMatchingTemplatesOnUpdateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminCreateSessionsTemplateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtilTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionTemplateComparatorTest.kt
Introduce new api endpoint to check matching session templates on create or update session template.
Admin API improvements
> VB-2576 api endpoint to check matching session templates

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
VB-2651 Missing room name on update session template
Fixes tech defect, missing room update for session template
> VB-2651 Missing room name on update session template

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/SessionTemplateAdminController.kt
Update swagger api to have session template validation errors, improve api documentation
> Update swagger api to have session template validation errors

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/LocationGroupAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonerCategoryGroupsAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonerIncentiveGroupsAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/SessionTemplateAdminController.kt
Update swagger api for validation errors
> Update swagger api for validation errors

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Extra performance improvements as casing prevents indexing.
> Extra performance improvements for book count.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prison/api/PrisonerHousingLevels.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/notification/VisitNotificationEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryVisitEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
- src/main/resources/db/migration/V2_32__add__visit_notification_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/FlagVisitsTaskTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationServiceTest.kt
Vb 2711 implement non association for sqs   storage
> Vb 2711 implement non association for sqs   storage

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestVisitNotificationEventRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationServiceTest.kt
Vb 1939 implement non association   extra logic to prevent duplicates
> Vb 1939 implement non association   extra logic to prevent duplicates

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/notification/VisitNotificationEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/EventAuditRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/resources/db/migration/V2_32__add__visit_notification_event_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestEventAuditRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventServiceTest.kt
Refactored a number of things we now store the reference not the visit id, also added a few missing telemetry items.
> Vb 1939 implement non association   refactored a number of things we now store the reference not the id, also added a few missing telemetry items. 

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/reporting/SessionVisitCountsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/VSIPReport.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/VSIPReporting.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VSIPReportingRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryVisitEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/repoting/VisitsReportingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/ReportingTask.kt
- src/main/resources/application.yml
- src/main/resources/db/migration/V2_33__add__vsip_reporting_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/ReportVisitCountsTaskTelemetryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/ReportVisitCountsTaskTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Session capacity reporting
Adds feature to report on session capacity and take up on a daily basis
> Vb 2722 get one off report showing session capacity and take up

- build.gradle.kts
Update dependencies based on dps-gradle-spring-boot updates as a fix for security issues.
Updates dps-gradle-spring-boot dependencies.
Security fixes
> Update dependencies based on dps-gradle-spring-boot updates

- .circleci/config.yml
- Dockerfile
Update JRE version to 20.
Update JRE version to 20.
> Update JRE version to 20.

- helm_deploy/values-dev.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/ExpiredVisitTaskConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/FlagVisitTaskConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/ReportingTaskConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/ReportingTask.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
VB-272 refactor and update to values-dev.yaml to allow testing on dev.
VB-272 refactor and update to values-dev.yaml to allow testing on dev.
> Vb 2722 get one off report showing session capacity and take up refactor

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PersonRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerReceivedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerReleasedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/VisitorRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
VB-1536 Proactively manage bookings, added endpoints for new notifications
> Vb 1536 proactively manage bookings, added endpoints for new notifications

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PersonRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerReceivedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerReleasedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/VisitorRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
Vb 1536 proactively manage bookings, added enpoints for new notifications
> Vb 1536 proactively manage bookings, added enpoints for new notifications

- .circleci/config.yml
- Dockerfile
- build.gradle.kts
Merge main branch changes into develop
Merge main branch changes into develop
> Merge main to develop 20230926

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerReleasedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/ReleaseReasonType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/NotificationEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/NonAssociationVisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/NotificationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt
Prisoner released events are processed
> VB-2760 Prisoner released events are processed

- docker-compose-local.yml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/NonAssociationsApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prison/api/OffenderNonAssociationDetailDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrationIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/HmppsAuthMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/NonAssociationsApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithLocationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/FlagVisitsTaskTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/NonAssociationVisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerValidationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/PrisonerSessionValidatorTest.kt
- src/test/resources/application-test.yml
> Main into develop

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/PrisonerOffenderSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/EventAuditRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/NonPrisonCodeType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/NotificationEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/NonAssociationVisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerVisitRestrictionChangeNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventServiceTest.kt
VB-2762
https://dsdmoj.atlassian.net/browse/VB-2762
Prisoner restriction change events are processed
> VB-2762 Prisoner restriction change events are processed

- .circleci/config.yml
> added a test job

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/CountVisitNotificationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/NotificationTestBase.kt
implementation of code to return the notification count
> Vb 3039 proactive bookings create server side endpoint to get information back on the notification count, implementation

- helm_deploy/visit-scheduler/Chart.yaml
Updates to helm chart versions for upgrading kubernetes to 1.25.
Updates to helm chart versions for upgrading kubernetes to 1.25.
> Updates to helm chart versions for upgrading kubernetes to 1.25.

- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/JwtAuthHelper.kt
Dependency updates as a fix for security issues.
Dependency updates as a fix for security issues.
> Dependency updates as a fix for security issues.

- build.gradle.kts
- helm_deploy/visit-scheduler/Chart.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/JwtAuthHelper.kt
Found defect in notification code, the type was hard coded
> VB-3054 Found a bug in the notification code

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/NonAssociationsApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/NonAssociationsApiMockServer.kt
Was using the wrong URL for new NA api
> VB-3054 Found bug with NA url, added correct URL

- .circleci/config.yml
> modified tests

- src/main/resources/db.scripts.mvp/update_visit_times_AYI.sql
Update incorrect booked visit times for Aylesbury (AYI)
> VB-3121 Update incorrect booked visit times for Aylesbury (AYI)

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerVisitRestrictionChangeNotificationControllerTest.kt
Start and end date for restriction, I was not including this originally because I've been told the dates are not used correctly in NOMIS, but I have changed my mind
> Vb 2762 we were not including the start and end date

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/RequestSessionTemplateVisitStatsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminMoveTemplateVisitsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateVisitStatsTest.kt
> Merge main into develop

- src/main/resources/db.scripts.mvp/migrate_visits_to_new_template_for_prison_MTI.sql
Migrate 2 visits from one session template to another
> VB-3183 Migrate 2 visits from one session template to another

- .circleci/config.yml
Just a work in progress but may be something like this will work
> VB-3186 attempt at fixing main/develop testing branch

- .circleci/config.yml
> VB-3186 merge main into develop with new config changes

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/NotificationGroupDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerVisitsNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
Create Dummy endpoints in VSiP service via orchestration service
> VB-3190 Create Dummy endpoints in VSiP service via orchestration service

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerVisitsNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/EventAuditRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/CountVisitNotificationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/CreateNonAssociationVisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/FutureNotificationVisitGroupsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerVisitRestrictionChangeNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestVisitNotificationEventRepository.kt
create service side code in v si p service to group notifications by type
> Vb 3192 create service side code in v si p service to group notifications by type

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
- helm_deploy/visit-scheduler/values.yaml
VB-3115 -
- set productId to DPS035
- remove contextColour, v1_2_enabled and v0_47_enabled as these are no longer needed.
set productId to DPS035 
VB-3115
> VB-3115 - set productId to DPS035

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/builder/VisitDtoBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/builder/VisitDtoBuilderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrationIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/ChangeBookedVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/ReserveSlotTest.kt
Staff cannot update booked visit with mismatched session time
> VB-3236 Staff cannot update booked visit with mismatched session time

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonAdminController.kt
VB-3233 Swagger doc incorrect!
> VB-3233 Swagger doc incorrect!

- src/main/resources/db.scripts.mvp/remove_migrated_video_call_ visits_for_phase_b_prisons.sql
- src/main/resources/db.scripts.mvp/remove_migrated_video_call_ visits_for_phase_c_prisons.sql
Deletes visits that are less then 45 minutes from DB for Phase B and Phase C prisons.
Data migration clean up.
> VB-2763 - add sql script to delete video call visits that are in Prod.

- .trivyignore
- build.gradle.kts
Updates build dependencies.
Fix for security failures.
> Update visit-scheduler dependencies as a fix for security failures.

- .circleci/config.yml
Update circle-ci orb version and jdk-tag.
Deploy to dev failing.
> Update circle-ci orb version and jdk-tag.

- Dockerfile
update jdk version on Dockerfile
update jdk version to 21
> update jdk version on Dockerfile

- .circleci/config.yml
Updating Docker image for UI tests in Config file
UI tests upgraded to latest Spring
> docker image updated

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/GetVisitNotificationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/NotificationTestBase.kt
Vb 3349 visit scheduler service, api changes and sql query to return notifications
> Vb 3349 visit scheduler service, api changes and sql query to return notifications

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitTest.kt
Fixes a small bug in VB-1845 code fix
Restrict future visits migrated
> VB-1845 restrict visits migrated to n number of days minor fix

- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_all.cqx.pjv.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_dal.hvz.pmd.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_gal.uvd.asy.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_jal.hng.xpr.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_kal.hen.ylo.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_lll.isg.pgm.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_mal.ueo.jlj.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_nal.hsp.mqv.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_nll.cbq.mxg.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_oal.cqj.lbs.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_oll.fee.bdp.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_qal.uxm.baj.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_ral.cqa.oge.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_sal.iyz.vqo.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_sll.czo.gja.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_val.hpg.dgb.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_wal.uzl.dep.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_yal.hop.mom.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_yll.feo.lje.sql
- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_zll.czm.zyl.sql
Bristol migration scripts.
Bristol migration scripts to be run on Live to move visits between sessions due to timetable changes at Bristol
> Bristol migration data scripts - created by Simon for migration of visits between Bristol sessions post timetable changes.

- src/main/resources/db.scripts.mvp/bristol_data_migration_20240112/BLI_migrate_bal.fps.lrp.sql
Add script for session template move. 
Add script for session template move.
> Bristol migration data scripts - add script for session template moves.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateVisitCountsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateVisitStatsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateVisitStatsTest.kt
Fixed up JSON stats structure to separate visits from canceled visits.
> Fixed up JSON stats structure to separate visits from canceled visits.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt
- src/main/resources/db/migration/V3_04__insert_data_into_application_contact_table.sql
- src/main/resources/db/migration/V3_05__insert_data_into_application_visitors_table.sql
- src/main/resources/db/migration/V3_06__data_into_application_support_table.sql
- src/main/resources/db/migration/V3_09__add_indexes_for_application_changes.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelNegativeDayLimitConfiguredTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitHistoryByReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeBookedVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeReservedSlotTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeReservedSlotThatHasABookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ReserveSlotTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestSessionTemplateRepository.kt
Added some enhanced tests, to improve test coverage
> VB-3335 Added some new tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/FutureVisitsSearchTest.kt
Removes visit status check on future visits API call.
Improvements.
> VB-3456 updates based on code review.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/builder/VisitDtoBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/builder/VisitDtoBuilderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ApplicationEntityHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByFilterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeBookedVisitTest.kt
Changes to fix updating ok booking,.. results were not being saved now they are
> Changes to fix updating ok booking,.. results were not being saved

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByFilterTest.kt
Fixes sort order on visits for prisoner page.
Code improvements.
> Update sort order on prisoner visits page and update affected tests.

- README.md
- src/main/resources/application.yml
This adds some documentation, plus increased time out on DB pools
> VB-3545 PreProd Application script was slow to deploy

- src/main/resources/application.yml
> Add statement timeout config

- src/main/resources/db/migration/V3_12__speed_up_visits_searches.sql
adds a index to the visit table
to speed up searches
> Vb 3547 performance issue with application/vistis

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/visit-scheduler/values.yaml
Problems with dev and staging, these settings are not required here.
> Moved livenessProbe and readinessProbe in prod and preprod only

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> Revert config for after migration script

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/PrisonerSessionValidator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitSessionMatchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrationIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/PrisonerSessionValidatorTest.kt
Matches session template for temporary locations during migration.
VB-3452
> VB-3452 changes to match session template during migration

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
Remove includeLocationGroupType flag from UpdateSessionTemplateDto
Code improvements
> Remove includeLocationGroupType flag from UpdateSessionTemplateDto

- src/main/resources/db.scripts.mvp/update_bullingdon_sessions_2024-03-18.sql
Updates session templates for future visits from old session template to new session template.
SQL changes - as the same cannot be achieved via Admin API.
> Update Bullingdon session templates from old session to new session.

- src/main/resources/db.scripts.mvp/update_bullingdon_sessions_2024-03-18.sql
Updates session slot Ids for affected visits.
Manual data correction
> Update visit slots and session slots for newly created session templates for Bullingdon.

- src/main/resources/db.scripts.mvp/update_hull_sessions_2024-03-25.sql
Updates session slots for Hull
Timetable changes - less thn 28 days notice - Hull
> Update Hull sessions to move visits from old to new sessions to accommodate timetable updates.

- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
Updates dependencies 
Fix security failures
> Updates to dependencies and minor changes for failing tests.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/UpdatePrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Prison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonsService.kt
- src/main/resources/db/migration/V3_21__add_visitor_config_to_prison_table.sql
- src/main/resources/messages.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonConfigTest.kt
Added new config for prisons to allow for 
Max visitors and adult age
> VB-3723 Add age config to VSIP prison API and database

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
Needed to add logging to work out why automated tests are not working
> Vb 3443 add automation tests, automated tests not working need to add logging to work out why

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/AvailableVisitSessionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt
new endpoint to get only available sessions
VB-3698
> VB-3698 - new endpoint to get only available sessions

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/AvailableVisitSessionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt
Adds visitRestriction to AvailableSessionDtp
VB-3698
> Vb 3698 create new session vsip endpoint that includes filters update

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitPrisonsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonUserClientDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/UserType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Prison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/PrisonUserClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/PrisonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/PrisonUserClientRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
- src/main/resources/db/migration/V3_22__add_prison_user_client_to_prison_table.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/ReportVisitCountsTaskTelemetryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/GetVisitPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestPrisonUserClientRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventServiceTest.kt
Allow for PUBLIC and STAFF supported prisons
> VB-3719 and VB-3718 to allow for PUBLIC and STAFF supported prisons

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/AvailableVisitSessionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/SessionType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt
Replace VisitRestriction with SesssionType as parameter for GET available sessions.
VB-3698
> Vb 3698 create new session vsip endpoint add session type

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/application/ChangeApplicationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/application/CreateApplicationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/application/SessionRestriction.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/AvailableVisitSessionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/SessionType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitHistoryByReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeBookedVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeReservedSlotTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeReservedSlotThatHasABookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ReserveSlotTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonExcludeDateNotificatonEventsTest.kt
Remove SessionType and replace with SessionRestriction.
VB-3698
> Vb 3698 create new session vsip endpoint session restriction

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
add to available sessions to check prisoner has closed restrictions,
Also changes api to use dates instead of min max on VSiP
> Vb 3800 add to available sessions to check prisoner has closed restrictions

- src/main/resources/db.scripts.mvp/R__Session_Template_Data.sql
Update DB Script to allow for changes to the DB structure.
> VB-3822   Update Default DB script

- .gitignore
- src/main/resources/db.scripts.mvp/VB-3838_Update_BFI_migrated_visits_to_correct_start_and_end_time.sql
Fixes up migrated data in DB
To make sure booking can be altered after migration see VB-3838
> VB-3838 Update BFI migrated visits to correct start and end time

- .gitignore
- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt
- src/main/resources/db.scripts.mvp/VB-3838_Update_BFI_migrated_visits_to_correct_start_and_end_time.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrateVisitSessionMatchTest.kt
> Merged main into develop

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/AvailableVisitSessionDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt
added sessionTemplateReference to AvailableVisitSessionDto
> added sessionTemplateReference to AvailableVisitSessionDto

- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitTest.kt
> fix-up-tests

- .circleci/config.yml
We want to introduce trunk based feature branches.
Rework the main workflow to be exclusively for main.
Add a new feature workflow which is for feature branches and terminates
at staging.
> Update circle ci to allow feature branches

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/ApplicationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
fix for VB-3942 
Code fix -Live Issue
> VB-3942 - fix for non association checks not filtering out visits with different session templates but on same date

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prison/api/OtherPrisonerDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/ApplicationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Visits being checked for different prisons
Live issue
> Vb 3942 non association checks not filtering out affected visit sessions update

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/builder/VisitDtoBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/ApplicationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/WebTestClientConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/DoubleBookingVisitTest.kt
> VB-3954 Fix to double booking issue.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/UnFlagEventReason.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prisonersearch/PrisonerSearchResultDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonOffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReceivedVisitNotificationControllerTest.kt
Added extra functionality to un-flag visits which have been previously flagged, if a prisoner returns to that prison.
https://dsdmoj.atlassian.net/browse/VB-2761
> Feature: Prisoner transfer events are processed

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/PublicVisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitEventAuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/VisitAssertHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/PublicVisitsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByFilterTest.kt
implement end point to return future visits by reference
VB-3916
> VB-3916 Get visits by booker reference

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/NotificationTestBase.kt
Adds visitorIds to app insights
VB-4001
> Vb 4001 add visitor ids to app insights

- .trivyignore
- build.gradle.kts
Upgrade to latest kotlin 2.0 and spring-boot 3.3.0
> Upgrade to latest kotlin 2.0 and spring-boot 3.3.0

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
> Update minor deps

- Dockerfile
Update certificate retrieval on docker-file
> Update certificate retrieval on docker-file

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/PublicVisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/FuturePublicVisitsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/PastPublicVisitsTest.kt
> VB-3616 Past bookings page - MVP

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prison/api/VisitBalancesDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/exception/OverCapacityException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationValidationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerSessionValidationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ApplicationEntityHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitValidationTest.kt
Adds validations during the booking process.
VB-4066
> Vb 4066 backend validations public booking mvp booking

- src/main/resources/db.scripts.mvp/VB_4184_update_bni_location_groups.sql
Update BNI location groups
VB-4184
> VB-4184 - script to update location group for BNI as requested.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonerDto.kt
> Update incorrect schema tag

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/VisitSchedulerExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/AssertHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitValidationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/DoubleBookingVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeReservedSlotThatHasABookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ReserveSlotTest.kt
Update validation error response to return error code 422 instead of error code 400
Code review
> Update error response

- src/main/resources/db.scripts.mvp/remove_migrated_visits_for_PVI.sql
Fixes migration issues.
Fix migration issues.
> SQL script to remove incorrectly migrated visits (and applications) for PVI

- .circleci/config.yml
Move Slack alert channels
Use new channels
> Move Slack channels

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/ApplicationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt
Replace lookup of createdBy field with a join between application and event_audit
VB-4231
> Changes for VB-4231 - join with event_audit and actioned_by to get creator details.

- .circleci/config.yml
use context instead of hard coding env vars in pipeline
> use context instead of hard coding env vars in pipeline

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
Add log line to help with finding root cause of 500 error
> Add log line to help with finding root cause of 500 error

- src/main/resources/db.scripts.mvp/update_sudbury_session_2024-08-09
This fixes any Saturday PM Sessions that need their times updating.
Ensure visits take place at the right time.
> Fix for moving Sudbury sessions to new timings

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/PublicVisitController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PublicVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitEventAuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/CapitaliseUtil.kt
- src/main/resources/db.scripts.mvp/update_sudbury_session_2024-08-09
Initial commit which contains a needed rework of some services to start splitting them into their own concerns. By untangling these services we can begin working to separate the event publishing out of the transaction for creating/updating/cancelling visits
> VB-4368 - Move event publishing outside of transaction - Part 1

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/ApplicationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt
Exclude application availability count for current users old applications.
> VB-4200 - Exclude application availability count for current users old applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/EventAuditRepository.kt
> Fix accidental adding of UPDATED_VISIT twice

- gradle.properties
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonExcludeDateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/PrisonExcludeDate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/resources/db/migration/V3_28__add_actioned_by_prison_exclude_date.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonConfigTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonExcludeDatesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonExcludeDateNotificatonEventsTest.kt
Add actioned_by to prison_exclude_date table
VB-3739
> VB-3739 created by field for blocking date

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonExcludeDatesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonExcludeDateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/TelemetryVisitEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonExcludeDatesTest.kt
Adds app insights data when adding / removing exclude dates.
VB-4194 and VB-4195
> VB-4194 and  VB-4195 -  add app insights data for add and remove exclude dates

- gradle.properties
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonAdminController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonExcludeDatesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonExcludeDateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/TelemetryVisitEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/PrisonExcludeDate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/PrisonExcludeDateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/main/resources/db/migration/V3_28__add_actioned_by_prison_exclude_date.sql
- src/main/resources/messages.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonConfigTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonExcludeDatesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonExcludeDateNotificatonEventsTest.kt
Staff Block date - backend feature
Staff Block date - backend tickets implemented
> Feature vb 3564 staff block date for social visits

- gradle.properties
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionSlotService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/reporting/VisitCountsByDateReportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/reporting/VisitsReportingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/ReportingTask.kt
Restructures the code for VSIP reporting
Code improvements.
> Vsip report restructure

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/config/ReportingTaskConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/TelemetryVisitEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/reporting/OverbookedSessionsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionSlotService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/reporting/OverbookedSessionsReportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/reporting/VisitCountsByDateReportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/reporting/VisitsReportingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/ReportingTask.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/OverbookedSessionsReportTaskTest.kt
VB-4505 - add report for overbooked sessions
VB-4505 - add report for overbooked sessions
> VB-4505 feature - VSIP reporting report overbooked sessions

- .circleci/config.yml
Follow up ticket to reduce contexts.
VB-4523
> VB-4523 - Update CircleCI contexts to reduce number of contexts.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerVisitsNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitEventAuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/FutureNotificationVisitGroupsTest.kt
Instead of returning a string to the orchestration, return all possible options and let the orchestration choose what to do for each (staff, public, system)
https://dsdmoj.atlassian.net/browse/VB-4521
> VB-5421 - Display the correct name for "Needs Review" page

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionTest.kt
Allows the frontend to retrieve a single visit session and all it's details.
https://dsdmoj.atlassian.net/browse/VB-4528
> VB-4528 - New endpoint to get a single session

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonExcludeDatesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/reporting/VisitCountsByDateReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonConfigTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/prison/PrisonExcludeDatesTest.kt
Removes exclude dates from PrisonDto
VB-4286
> VB-4286 remove excluded dates from PrisonDTO

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/validators/UpdateSessionTemplateValidator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
Remove validation to reduce session capacity below booked visit counts.
VB-4529
> VB-4529 - remove validation to reduce session capacity below booked visit counts.

- src/main/resources/db.scripts.mvp/fix_NWI_sessions.sql
Fixes NWI new sessions with locations
Ensures correct prisons are on correct sessions
> VB-4544 - Fix Norwich issues

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/OutcomeStatus.kt
Add booker_cancelled as new outcome status type for public bookings
> Add booker_cancelled as new outcome status type for public bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/resources/db/migration/V3_30__add_index_on_type_column_for_event_audit_table.sql
Optimise 3 queries which have been identified as slow (more than 3 seconds to execute) by indexing the type column on event_audit and optimising the query structure.
> VB-4752 - Improve slow database query performance

- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByDateTest.kt
fix failing integration test missing email parameter
> fix failing integration test missing email parameter

- .circleci/config.yml
Updates Circle CI orb to version 10.
Update orb to latest version
> Update Circle CI orb to version 10.

- src/main/resources/db.scripts.mvp/delete_duplicate_visits_post_migration_20241128.sql
Delete duplicate visits
Delete duplicate visits as a result of 2 migration processes running in parallel for CWI
> Delete duplicate visits 

- helm_deploy/values-preprod.yaml
Reduce number of preprod instances to 2
Reduce number of preprod instances to 2 as 4 instances are not needed on preprod.
> Reduce number of preprod instances to 2

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PublicVisitService.kt
Instead of returning the visit references, just return the visits instead.
> Remove duplicate call to visit-scheduler db

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-staging.yaml
Updates the alert severity channels
So errors/alerts are reported to us
> VB-4970: Update nonprod alertseverity

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionScheduleTest.kt
VB-4960 - add visit room to SessionScheduleDto
Return visitRoom as part of SessionScheduleDto
> VB-4960 - add visit room to SessionScheduleDto

- .circleci/config.yml
Updated config.yml to include Staff playwright-e2e tests
Replacing Selenium tests with Playwright
> add playwright tests to the pipeline

- .circleci/config.yml
Job on main pipeline should have  "only" for filter.
> correct filter for job

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitStoreService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/UpdateVisitTest.kt
Add updates to visit data being sent to telemetry service in case a visit is being updated.
VB-5056
> Add custom event attributes sent to appInsights on visit update

- helm_deploy/values-dev.yaml
> correct shutdown config

- .circleci/config.yml
Updates Slack releases channel
To update Slack releases channel
> Update Slack releases channel

- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/JwtAuthHelper.kt
> fix warning for keyPair on JwtAuthHelper

- applicationinsights.json
- src/main/resources/logback-spring.xml
> swap logging from debug to info

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/NotificationEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/FlagVisitsTask.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/FlagVisitsTaskTest.kt
Minor changes to flag visits report based on feedback from @simonnebMOJ 
Flag visit report improvements.
> Minor changes to flag visits report.

- helm_deploy/visit-scheduler/values.yaml
Errors appeared after upgrading dps-spring-boot to 7.1.0. This is the fix
> Use application-insights secret for connection string to fix deserialisation errors

- .circleci/config.yml
Update the version on the image
Fix failing test
> Update the image version of Playwright

- helm_deploy/visit-scheduler/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/FlagVisitsTask.kt
- src/main/resources/application.yml
Update logging levels on FlagVisitsTask and update number of days ahead to 21.
Improve logging and update report to next 3 weeks.
> Update logging levels on FlagVisitsTask and update number of days ahead to 21.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/builder/VisitDtoBuilder.kt
> Adding new clientRef and clientName to visits models

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/UnFlagEventReason.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrationIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/MigrateCancelVisitTest.kt
VB-5362 - handle visit cancellations on NOMIS and minor code improvements.
handle visit cancellations on NOMIS
> VB-5362 - handle visit cancellations on NOMIS and minor code improvements.

- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/MigrateCancelVisitTest.kt
Adds a test for past dates
Adds a test for past dates
> VB-5362 - add test for visit cancellations of past dates.

- src/main/resources/db.scripts.mvp/fix_LLI_update_session_slots.sql
Update to session slot script - crated by @simonnebMOJ 
Session slot updates for LLI
> checking in Long Lartin script - created by Simon N

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt
Minor updates to swagger docs
Minor updates to swagger docs
> Update swagger docs.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/client/PrisonerContactRegistryClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonerContactRegistryMockServer.kt
Change calls to use /v2 endpoints.
Use latest prisoner contact registry endpoints.
> VB-5443 - Update prisoner contact registry client to use /v2 endpoints.

- src/main/resources/db.scripts.mvp/VB_5555_WDI_sessions.sql
WDI migration script 
Fix for VB-5555
> added WDI migration script VB-5555

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/NotificationEventAttributeType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PersonRestrictionUpsertedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/VisitorRestrictionUpsertedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PersonRestrictionUpsertedNotificationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/VisitorRestrictionUpsertedNotificationControllerTest.kt
This will be used by the frontend to highlight changes to specific restrictions for visitors
https://dsdmoj.atlassian.net/browse/VB-3758
> Add new attribute restrictionId to visitor restriction events

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SnsService.kt
We are hoping this will help cut down the amount of publish domain event exceptions we see on visit-scheduler, by having retries.
> Add retry by using default logic in hmppsTopic publish method

- src/main/resources/db.scripts.mvp/remove_location_group_from_leeds_session_templates.sql
Updates DB to remove location group from session templates.
Request from prison
> Delete location group "wbc~gvl~sdv" from all LEI session templates.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
Staging seems to be returning different data to dev for sessions. These logs will hopefully show us some general stats on whats happening without exposing too much data.
> Add more logging

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/validators/UpdateSessionTemplateValidator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
Add include type flags to UpdateSessionTemplateDto
VB-5667
> Add include type flags to UpdateSessionTemplateDto

- src/main/resources/db.scripts.mvp/fix_LEI_sessions.sql
Fixes issues with Leeds timetables. All past visits and future visits should be migrated to new session templates.
Ensures correct prisoners are offered the right sessions
> Update to fix LEI (Leeds) timetable

- src/main/resources/db.scripts.mvp/fix_HHI_sessions.sql
Fixes sessions for Holme House.
Ensures prisoners get the correct visit sessions.
> Fix for Holme House sessions

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionDetailsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionTemplateMapper.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/matchers/SessionGroupMatcher.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/matchers/SessionLocationMatcher.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/validators/UpdateSessionTemplateValidator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
Add validations exclude update session template endpoint
VB-5667
> VB-5667 add validations exclude update session template endpoint

- src/main/resources/db/migration/V4_0__add_visit_sub_status_to_visit_table.sql
Update visit_sub_status script as it is failing on preprod due to queries not finishing on time.
workaround for failure to run flyway scripts on preprod in time
> Update visit_sub_status script as a fix for performance issues.

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonerDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitRequestSummaryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prisonersearch/PrisonerSearchResultDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitRequestsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonOffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookARequestedVisitFeatureEnabledTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitValidationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CountVisitRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerValidationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionCategoryValidatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionIncentiveLevelValidatorTest.kt
Add new endpoint to get list of visit requests for a prison. Will be used by new visit requests tile to show all in a table.
https://dsdmoj.atlassian.net/browse/VB-5682
> VB-5682 - Get list of visit requests for prison

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminGetSessionsTemplateLocationsWhenPrisonerIsTransitionalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionCapacityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsByUserTypeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsDoubleBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithCategoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithExcludeLocationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithIncentivesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithLocationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithMultipleGroupsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Adds 1 day to the booking window to fix current functionality
Fix for VB-5790
> Vb 5790 update session dates returned

- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
> VB-5790 -fix failing test

- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
> VB-5790 - fix failing test

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitRequestsApprovalService.kt
- src/main/resources/messages.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/ApproveVisitRequestTest.kt
It's possible 2 users action the same visit, this will ensure the 2nd request is failed early.
> VB-5793 - Add validation to check visit is in correct status before approving or rejecting

- src/main/resources/db/migration/V4_1__add_visit_request_indexes_to_visit_table.sql
Add indexes for most common DB queries for visit requests
> Add indexes for most common DB queries for visit requests

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionSlotService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitEventAuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtil.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/diff/UpdateVisitDifferentiator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/diff/UpdateVisitSummaryUtil.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/UpdateVisitSummaryUtilTest.kt
adds an audit summary to detail what has changed on the visit
VB-5828
> VB-5828 - Add update visit audit text

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/FindCancelledPublicVisitsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/FuturePublicVisitsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/PastPublicVisitsTest.kt
Include REQUESTED_VISIT while returning BOOKED visits.
Public booking - request journey improvements.
> Update booked visit query public

- .circleci/config.yml
- .github/workflows/security_codeql_actions_scan.yml
- .github/workflows/security_owasp.yml
- .github/workflows/security_trivy.yml
- .github/workflows/security_veracode_pipeline_scan.yml
- .github/workflows/security_veracode_policy_scan.yml
- build.gradle.kts
Migrate security scans from circle-ci to github actions
> Migrate security scans from circle-ci to github actions

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/AutoRejectionReason.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ProactiveBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitEventAuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitRequestsApprovalRejectionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitRequestsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt
When a prisoner released event is consumed, booked visits will be flagged and request visits will be auto rejected
> VB-5437 - Prisoner released auto rejects visit requests

- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/AutoRejectionReason.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ProactiveBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitRequestsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/AutoRejectVisitRequestsTask.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReceivedVisitNotificationControllerTest.kt
Reject all request visits for prisoner outside of their current prison
https://dsdmoj.atlassian.net/browse/VB-5437
> VB-5437 - Request visits are auto rejected when prisoner transferred
