ministryofjustice/visit-scheduler

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoder.kt
Removed the letter 'S' from the list of separators.
To improve reference readability.
=> moved S from separator to excluded

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt
Locks visits for the scheduled delete expired reservation task
Prevent stale state warnings in the logs
=> lock on visit delete

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/CreateVisitRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/UpdateVisitRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/VisitSession.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/data/filter/VisitFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/Visit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/VisitRestriction.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/jpa/specification/VisitSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerService.kt, src/main/resources/db/migration/V1_0__create_visit_table.sql, src/main/resources/db/migration/V1_7__create_visit_restriction_column.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/resource/VisitSessionsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitSchedulerServiceTest.kt
Adds open / closed restriction to visit
Adds open / closed booked visit count to available session
Corrects defect in visit session end date criteria
Add booked slot count values to /visit-sessions endpoint to replace the hard coded values with actual counts
=> Vb 412 booked slot count

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoder.kt
Corrects a defect in the padding causing repeated chars in the reference.
The reference needs to be random and must contain only one of the separator chars.  The refactor changed the use of the separator char pool to also be used to generate the random padding which resulted in repeated char sequences.
=> VB-648 Defect in padding

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitControllerTest.kt
VisitController updated to include a status parameter on get visits endpoint
eg:
{{hostVisit}}/visits?visitStatus=BOOKED
Allows the client to filter visits by status
=> VB-661 Status query param added to get visits endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateContactOnVisitRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateVisitRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/CreateVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitControllerTest.kt
Removed migration code from create visit, because migration is handled via different end point 
To avoid POC issues, and to increase maintainability and a adaptability of code base
=> VB-749 Refactor current create visit endpoint to remove migration data

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateLegacyContactOnVisitRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/MigrateVisitRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/validation/NullableNotBlank.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/MigrateVisitTest.kt
Adds default migration value to null legacy telephone number to match existing default.
Adds nullable not blank Constraint Validator
Prevent inconsistent 500 response for null field
Improve migration request validation
=> VB-823 Contact update for null field and validation

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/CreateLegacyContactOnVisitRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/MigrateVisitTest.kt
Makes sure when JSON null type is use a Default is given
to fix a bug
=> VB-834 Migration - Nullpointer when Outcome status not provided

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/MigrateController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/MigrateVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Sets the pre-auth to a migration role independant of the visit scheduler roles
Prevent unauthorised access to the migration endpoint
=> VB-756 Migration endpoint restricted to migration roles

src/main/resources/db/migration/V2_05__fix_missing_application_reference_defect.sql
fixes `applicationReference` missing on existing bookings
to fix a bug, other wise old visits will not be avalable
=> VB-1225 `applicationReference` missing on existing bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitByReferenceTest.kt
Fixes a defect VB-1242 - Using getBookedVisit on /visits/{reference} should be allowing to get booked and canceled visits
to allow the cancellation sync code to get canceled Visits
=> VB-1242 Using getBookedVisit on /visits/{reference}

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/VisitStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/VisitTask.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/ChangeBookedVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/ChangeReservedSlotTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitSessionsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/CleanUpVisitsScheduleTest.kt
New approach reverted changes from this morning,
now uses status
it makes the booking count more accurate and does not mess up the confirm flow 
to help the use know how many slots are booked
=> VB-1213 Amending to solve booking count issue

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/ChangeReservedSlotTest.kt
When amending a `BOOKED` visit and the reserved slot changes, if the visit now matches the restriction and date/time of the `BOOKED` visit then move the status to `CHANGING` rather than keeping it `RESERVED`.
To make sure the status of the visit being amended matches what is happening and the capacity counts remain accurate.
=> VB-1251: Allow visit status to go from RESERVED to CHANGING

src/main/resources/application.yml
Update to run job every 10 minutes instead of an hour to delete any expired visits more than 20 (set in validity-minutes) minutes old.
Ensure expired visits are deleted at the earliest so that the slot is freed.
=> VB-1312 - Update cron for deleteTask job to run every 10 minutes.

src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
Tests were failing during certain times of week, also one other test was randomly failing (probably due to how JPA transactions persist objects)
to have reliable tests that actually pass and fail based on the code rather than flaws in the test
=> Vb 1339 fixup some of the get session tests

src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonApiMockServer.kt, src/test/resources/application-test.yml
This PR changes the test setup to use a random port when WireMock is started. Otherwise, the tests won't run if the machine that runs them already has something running on port `8092`.
Your friend from the [Testcontainers](https://github.com/testcontainers/testcontainers-java) project was looking at how the library is used in the wild, tried running tests and discovered the static port usage :)
=> Start Wiremock on a random port to avoid conflicts

.circleci/config.yml
Updating the CircleCI orbs version as a fix for the security failures… as recommended by Peter Philips.
e.g PR - https://github.com/ministryofjustice/hmpps-nomis-prisoner-api/pull/136
Updates the Circle CI orbs version
To update to the latest orbs version and also as a security fix.
=> Updating the CircleCI orbs version as a fix for the security failures

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitControllerLegacy.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByFilterTest.kt
it changes prison id to not required, however if a prison Id not present then a prisoner id must be, this is to prevent the hole DB from being downloaded 
To allow the consumer of the API to download all visits for a prisoners
=> VB-1403 GET /visits - prisonId shouldn't be a required parameter

helm_deploy/values-staging.yaml
turns off domain event's in staging
to prevent systems down stream from getting confused,... e.g. same visit references...
=> VB-1411 Turn off domain events on staging

src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/legacy/CancelVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelNegativeDayLimitConfiguredTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelZeroDayLimitConfiguredTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByFilterTest.kt
Moves nested classes out of CancelVisitTest as these were not running properly.
Fixes to tests to fix failures
=> Vb 1358 fix nested tests

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/main/resources/db/migration/data/R__clean_up_BOOKED_visits_with_SUPERSEDED_CANCELLATION.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/task/CleanUpVisitsScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/ChangeBookedVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestVisitRepository.kt
Some visits have turned up with a status of BOOKED and a outcome status of SUPERSEDED CANCELLATION
Fixes bug found in https://dsdmoj.atlassian.net/browse/VB-1537
To prevent DB data from being inaccurate...
=> VB-1537 Some visits have turned up with a status of BOOKED and a outcome status of SUPERSEDED CANCELLATION

src/main/resources/db.scripts.mvp/fix_up_future_visits_for_cardiff_post_release.sql, src/main/resources/db.scripts.mvp/fix_up_future_visits_for_preston_post_release.sql, src/main/resources/db.scripts.mvp/fix_up_future_visits_for_wandsworth_post_release.sql
VB-1763 - script to update visits for Cardiff, Preston and Wandsworth to ensure visit times to match the timetables provided by each prison.
Updates visits migrated for the 3 new prisons to be onboarded to update the visit timings with the data in the session templates.
Keep visit data in sync with session templates to allow these visits to be updated.
=> VB-1763 - script to update visits for Cardiff, Preston and Wandsworth

.circleci/config.yml
makes sure code is compiled to the correct version of the JDK
to get CI build working
=> VB-2005 Update VSiP Dependencies - change to CI JDK version

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitControllerLegacy.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/legacy/CancelVisitTest.kt
move the existing cancel endpoint to VisitCotrollerLegacy
Will ensure that the cancellations from NOMIS continue working till the new SYNC service endpoint is created.
=> Vb 2028 create a new v 2 endpoint for cancel visits till syscon migrates cancel over to the new endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/MigrateController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/MigrateVisitRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryVisitEvents.kt, src/main/resources/db.scripts.mvp/R__Session_Template_Data.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/MigrateVisitTest.kt
It prevents cancelation validation when migrated data from NOMIS
To allow migrated cancelations to take place from nomis
=> Vb 2040 defect sync cancel fails when visit is in the past

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/MigrateVisitRequestDto.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/MigrateVisitTest.kt
createdBy is now optional also added tests.
Sync process will be temporarily using old api without the created by details.
=> Make actioned by feild optional

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/VisitSchedulerApplication.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonConfigService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SupportService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/task/ScheduledCacheEvictTask.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/VisitSupportControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/config/GetSupportedPrisonsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/QuotableEncoderTest.kt, src/test/resources/application-test.yml
VB-2074 cache support types and supported prisons so that the data is not fetched from DB every time.
Caches support types and supported prisons and evicts the cache at regular intervals
Performance improvements.
=> VB-2074 cache support types and supported prisons

applicationinsights.json
removed the sampling as can still see the dependency logs o…n preprod.
Reduce dependency logging on prod and preprod
Reduce dependency logging as logs are being cluttered
=> VB-2096 - Reduce dependency logging on prod and preprod

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionCapacityDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionCapacityTest.kt
Removes multiple capacity dto's being returned when different capacity groups, it now adds them all up
Reduce UI change
=> Remove list of capacity objects from api

src/main/resources/db.scripts.mvp/Simple_set__Session_Template_Data.sql
Small error in sql script capacoty_group was still in sql script re verted back to visit_room
Sql would not run in preprod other wise
=> Still had capacoty_group in temp table

src/main/resources/db.scripts.mvp/back_populate_visits_with_session_ref.sql
SQL It looks forward 28 days and populates visits with the correct session template, does not work with migrated data
To make sure that all visits that are yet to happen are connected to session templates.
=> created sql script to backpopulate session template ref into visits

src/main/resources/db.scripts/test/R__VB-2248_Delete_DMI_migrated_visits.sql
Remove DMI migrated data from DB
To allow us to re migrate all DMI visits in prod
=> Delet all DMI migrated visits in prod

src/main/resources/application.yml
Moves the log non association run to 2 PM
Log non association visits on Live
=> Update schedule for logging non association visits

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/ChangeVisitSlotRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/ChangeReservedSlotTest.kt
Updates ChangeVisitSlotRequestDto to add sessionTemplateReference.
Fix for VB-2271.
=> Vb 2271 mismatch between available capacities causing overbookings

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/util/PersistVisitHelper.kt
This pull requests moves the update of the visit entity for booking and cancellation into a helper class, so the transaction can be complete before the domain events are sent (Domain events can take some time). Therefore other threads with the same action and details will use the latest persisted data. Hopefully duplicate requests will be caught by isApplicationBooked or isBookingCancelled and the existing details will be return with no additional process.   
To prevent duplicate events from being sent to the domain events and down stream actions will not be actioned.
=> Fix to resolve issues with multiple events being created

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminDeleteSessionTemplateTest.kt
add's validation to delete end point, if session template has visits then it cannot be deleted.
to make sure session templates can only be delete when there is no associated visits, to prevent live session templates being deleted
=> Vb 2321 delete api function on session templates add validation

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/CreateSessionTemplateDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionDateRangeDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionScheduleDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTimeSlotDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionTemplate.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/MigrationSessiontTemplateMatcher.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtil.kt, src/main/resources/db/migration/V2_27__n_weekly.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminCreateSessionsTemplateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitSessionMatchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionCapacityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtilTest.kt
- Introduce logic to server side
- Return results for display in the UI
- Create SQL scripts to migrate existing sessions that are not weekly
- Migrate logic
- Updates SessionScheduleDto to  use SessionTimeSlot and DateRangeDto
To allow n weekly to work, so that complex time tables can be catered for,... also refactor SessionScheduleDto to standardise approach.
=> VB-2358 Introduce logic to server side - n weekly

src/main/resources/db/migration/data/R__add_prison_codes.sql
Description
We need to remove the following dates from the social visits timetable for Cardiff:
12 7 2023 
19 7 2023
=> VB-2395 Block dates from Cardiff schedule in VSiP (CFI)

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/ApplicationMethodType.kt
Adds new value `NOT_APPLICABLE` to application method type.
Capturing application method type is for requests by visitors. This new NOT_APPLICABLE value is for cases where, for example, a visit might be cancelled by the establishment itself.
=> VB-2071 Add NOT_APPLICABLE application method type

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateVisitCountsDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateVisitStatsDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/projections/VisitCountsByDate.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateVisitsTest.kt
Updates the session template stats endpoint to include a list of visit dates and counts
Admin API improvements.
=> VB-2569 return list of visit dates and counts as part of visit stats endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/UpdateSessionTemplateValidator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
Updates validation around valid to date to looked for booked or reserved visits.
Admin API improvements.
=> VB-2470 add validation around updates of valid to date to allow updates if visits are cancelled.

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionServiceTest.kt
To fix a booking count issues, it now uses the session template start and end time to work out the booking count
=> Updated visit booked/reserved count check

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/NonAssociationChangedNotificationDto.kt
Implement non-association for SQS - create listener in orchestration, added endpoint to allow orchestration work to be complete
It adds an end point with dummy response.
to allow use to continue separate threads of coding work..
=> VB-2715 added end point with dummy response

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt
VB-2998 Updating session template removes selected groups in admin service, fixes a bug
=> Vb 2998 updating session template removes selected groups in admin service

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/RequestSessionTemplateVisitStatsDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminMoveTemplateVisitsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminSessionTemplateVisitStatsTest.kt
Updates visits stats to not have an end date.
VB-3172 fix
=> VB-3172 - update visitsToDate to be null so that all visits will be returned

src/main/resources/db.scripts.mvp/Remove_migrated_video_cal_ visits_for_AYI.sql
As part of the migrations for onboarding AYI, we included some video call visits that the establishment had put into the wrong NOMIS room.
We need toe remove these from the database so they do not appear incorrectly as SOCIAL visits.
=> VB-3197 Remove video call visits for AYI from database

.circleci/config.yml, helm_deploy/visit-scheduler/Chart.yaml, helm_deploy/visit-scheduler/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 0 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
=> Migrating project to use groups in allowlist

src/main/resources/db.scripts.mvp/BRI_xmas_move_visits_to_new_st.sql
Bristol (BSI) have asked for a significant change to their timetable over Christmas. There are some existing bookings from the ‘old’ deactivated session templates that need to be moved to the appropriate new session templates.
=> VB-3291-Move-Bristol-(BSI)-sessions-to-new-timetable

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestVisitNotificationEventRepository.kt
Removes any notification events associated with a visit reference from the visit notification event table.
VB-3358 requirements
=> VB-3358 - remove associated notification events with cancellation

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonExcludeDateNotificatonEventsTest.kt
Deletes any PRISON_VISITS_BLOCKED_FOR_DATE when the visit is updated and moved to a new date.
Fix issues
=> VB-3447 fix - delete PRISON_VISITS_BLOCKED_FOR_DATE visit notification events when the visit date is updated

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionSlotRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionSlotService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt, src/main/resources/db/migration/V3_19__add_session_slot_constraints.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/DataBaseTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminMoveTemplateVisitsTest.kt
add's constraint and try catch code to return the correct value if issue occurs
There is a race condition and in those cases a extra entry is entered into the DB, and all other visits for that slot then fail because the JPA query tries to return multiple results when only one is permitted.
=> VB-3621 Migration bug - found with duplicate data on session slots

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsBySessionTemplateFilterTest.kt
adds prisonCode as a parameter when getting visits by session template reference.
VB-3651 bug fix
=> Fix for VB-3651 - add prisonCode as a parameter when getting visits by session template reference.

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/UnFlagEventReason.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryVisitEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationFlaggingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/DeleteNonAssociationVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonExcludeDateNotificatonEventsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventServiceTest.kt
Creates unflag events when a notification event is removed.
Better AppInsights reporting.
=> Vb 3620 unflag events to be sent to application insights to help improve reporting

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/EventAudit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/main/resources/db/migration/V3_25__add_user_type_to_event_audit_table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ApplicationEntityHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/migration/MigrateVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeBookedVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ChangeReservedSlotThatHasABookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ReserveSlotTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/CreateNonAssociationVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonExcludeDateNotificatonEventsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerVisitRestrictionChangeNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/TestEventAuditRepository.kt
Added user Type to audit table, notifications, migrations, application and visits and cancelation of visits have been affected.
=> VB-3877 Add UserType to Application/Visit and Cancel actions

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonerDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/prisonersearch/PrisonerSearchResultDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerReceivedNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/mock/PrisonOffenderSearchMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReceivedVisitNotificationControllerTest.kt
After testing a new approach was needed due to the lastPrisonId not being updated to the correct prison.
New approach is to use current prison to flag all other visits and then check for current prison if any are flagged, then un-flag them.
https://dsdmoj.atlassian.net/browse/VB-2761
=> Feature: VB-2761 Prison transfer events processed

.circleci/config.yml
Fix owasp scan by providing jdk_tag of 21 and cache_key v2
=> Fix owasp scan by providing jdk_tag of 21 and cache_key v2

.circleci/config.yml
Updates the scheduled cron time for vera code scans. Currently it clashes frequently with other apps being scanned so fails.
Stop cron job clashes in veracode scans.
=> Update veracode cron time

helm_deploy/values-prod.yaml
After big data migration we need to change replicaCount back to 4 and remove bespoke time out
=> VB-4109 Return replicaCount back to 4 for prod

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/ApplicationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/application/ReserveSlotTest.kt
Changes for VB-4200 - send username as a parameter to getAvailableSessions so that reserved applications by the user for the same prisoner are ignored.
Fix for VB-4200
Bug fixes.
=> Changes for VB-4200 - send username as a parameter to getAvailableSessions

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitSessionController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ApplicationEntityHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsDoubleBookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithExcludeLocationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsWithLocationsTest.kt
Changes for VB-4202 - send username as a parameter to getVisitSessions so that reserved applications by the STAFF user for the same prisoner are ignored.
Changes for VB-4202 - send username as a parameter to getVisitSession so that reserved applications by the STAFF user for the same prisoner are ignored.
VB-4202
=> Changes for VB-4202 - send username as a parameter to getVisitSessions

build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/DoubleBookingVisitTest.kt
Add a new lib to allow us to retry a known flaky test 3 times before failing.
This test fails as there is minimal concurrency contorl in place for a visit being booked at exactly the same time.
=> Bug - Flaky test fix

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/EventAuditRepository.kt
When a visit is flagged, if it is a migrated visit, it will sometimes cause an error in production.
This is because the call to get notification groups has a result set of null during one of its calls to the database (which isn't allowed). This is due to the visit being a migrated visit and not having a BOOKED_VISIT event in the event audit table. It also hasn't been updated so it doesn't have an UPDATED_VISIT either.
Adding MIGRATED_VISIT to the query to make sure it never comes back null.
=> [BUG] - Get notification groups for PVI coming back with NPE

gradle.properties, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtil.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/utils/SessionDatesUtilTest.kt
This was due to how we aligned the date with the closest day of the week matching the template and the booking window start date.
Rework the logic to first align the date and then loop through using the frequency to get first future date.
Currently this is a crude fix, we're looking into optimising as templates can be created many years ago and this wouldn't be suitable for those due to the while loop constantly checking.
=> When frequency of session template is more than 4 weeks it was causing a bug of not displaying the session template

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonAdminController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonExcludeDatesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/PrisonExcludeDateDto.kt
Update PrisonExcludeDateDto to allow actionedBy as null till we remove the admin functionality of adding and removing exclude dates.
Update PrisonExcludeDateDto to allow actionedBy to be null for the time being
Backward compatibility with admin service.
=> Update PrisonExcludeDateDto to allow actionedBy as null 

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/NotificationGroupDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerVisitsNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/ProcessVisitNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/SaveVisitNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/notification/VisitNotificationEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/main/resources/db/migration/V3_29__add_visitorId_and_visitorRestrictionType_to_visit_notification_event_table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PersonRestrictionUpsertedNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/VisitorRestrictionUpsertedNotificationControllerTest.kt
When an event type is for a visitor, capture the additional information from that event in the visit_notification_event table.
VisitorId - The ID of the visitor who has had an event raised about them VisitorRestrictionType - For the visitor, what restriction has been added
Update the NotificationGroupDto to include new fields, ready to be returned to the orchestration and frontend.
https://dsdmoj.atlassian.net/browse/VB-4514
=> VB-4514 - Include additional information for visitor specific events

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/admin/PrisonExcludeDatesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionTemplate.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionTemplateExcludeDate.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateExcludeDateRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt, src/main/resources/db/migration/V3_30__add_session_template_exclude_dates.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetAvailableSessionsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionsTest.kt
VB-4654 - adds new session_template_exclude_date table and add code to not return sessions for blocked dates.
Block individual sessions only.
=> VB-4654 - add new session_template_exclude_date table and add code to not return sessions for blocked dates.

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionService.kt, src/main/resources/db.scripts.mvp/fix_NMI_session_part_2.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/session/GetSessionTest.kt
The booked count will be used by frontend for displaying "Fully booked" session information. So we don't need to include reservations, only booked count.
https://dsdmoj.atlassian.net/browse/VB-4687
=> Bug fix - Exclude reservations from the "Get single session" endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/SnsDomainEventPublishDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/audit/EventAuditDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/MigrateVisitService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SnsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/events/SendDomainEventTest.kt, visit-scheduler-event-specification.yaml
This id will be used by gov notify further down stream as a reference for each notification to tie it to an entry in the event_audit table.
https://dsdmoj.atlassian.net/browse/VB-4908
=> VB-4908 - Include event audit id in the HMPPS domain events

src/main/resources/db/migration/V3_33__remove_outdated_backup_tables.sql
These were added a long time ago when application tables were being introduced. They were intended to be temporary and dropped eventually. Finally cleaning these up.
=> Remove old temporary _backup tables

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/VisitNotifyHistory.kt
add missing  @Enumerated(EnumType.STRING) to status in VisitNotifyHistory
Bug fix
=> Status in VisitNotifyHistory not an Enumerated type

helm_deploy/values-prod.yaml
Update generic-prometheus-alerts.alertSeverity to visits-alerts to redirect prod alerts to visits Slack channel
Update generic-prometheus-alerts.alertSeverity to visits-alerts on prod
redirect prod alerts to visits Slack channel
=> Update generic-prometheus-alerts.alertSeverity to visits-alerts

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerAlertCreatedUpdatedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerVisitRestrictionChangeNotificationControllerTest.kt
VB-4934 fix - Replace getFutureVisitsBy with getFutureBookedVisits on VisitNotificationEventService to ensure only BOOKED visits are flagged.
VB-4934 fix
=> VB-4934 fix - Flag only future visits.

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitStoreService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt
VB-5009 - update cancellation validation to not let public cancel visits that have already started.
VB-5009 fix to not allow cancellation of visits that have already started.
=> VB-5009 - update cancellation validation for usertype - PUBLIC

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/FindCancelledPublicVisitsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/FuturePublicVisitsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/PastPublicVisitsTest.kt
VB-4918 fix - update past visits as before current date and time and future visits as after current date and time
VB-4918 fix
=> VB-4918 fix - update past visits and future visits criteria

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/NotificationEventAttributeType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerVisitsNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/ProcessVisitNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/SaveVisitNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/VisitNotificationEventAttributeDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/notification/VisitNotificationEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/notification/VisitNotificationEventAttribute.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/main/resources/db/migration/V3_36__visit_notification_event_rework_new_attribute_table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PersonRestrictionUpsertedNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerAlertCreatedUpdatedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReceivedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerVisitRestrictionChangeNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/VisitorRestrictionUpsertedNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/VisitorUnapprovedVisitNotificationControllerTest.kt
This commit introduces the ability for visit notification event entries to have additional attributes associated with them. A new table will hold these attributes with a relationship to the primary visit notification event table of One-To-Many (where visit_notification_event is One, visit_notification_event_attribute is Many).
Service layer will return the attributes with flagged visits, for frontend service to use to better display information on the visit booking details page.
https://github.com/ministryofjustice/visit-scheduler/pull/914
=> VB-4411 - Visit booking details rework

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/NotificationEventAttributeType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/PrisonerVisitsNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/ProcessVisitNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/SaveVisitNotificationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/visitnotification/VisitNotificationEventAttributeDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/notification/VisitNotificationEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/notification/VisitNotificationEventAttribute.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/main/resources/db/migration/V3_36__visit_notification_event_rework_new_attribute_table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PersonRestrictionUpsertedNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerAlertCreatedUpdatedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReceivedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerVisitRestrictionChangeNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/VisitorRestrictionUpsertedNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/VisitorUnapprovedVisitNotificationControllerTest.kt
This PR introduces "attributes" to the visit event notifications. These attributes allow for extra information to be captured for specific event types. Currently only 3 events (VISITOR_RESTRICTION_UPSERTED_EVENT, PERSON_RESTRICTION_UPSERTED_EVENT, VISITOR_UNAPPROVED_EVENT) have extra fields, but this new design allows new fields (attributes) to be added dynamically to the new attributes table with little changes required to the code itself.
https://dsdmoj.atlassian.net/browse/VB-4411
https://dsdmoj.atlassian.net/browse/VB-5040
=> VB-4411 - Feature - Visit booking details page rework

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitNotificationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/ClientHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/CountVisitNotificationTest.kt
Restricts notification counts by notification types passed
Fix for VB-5148
=> VB-5148 - allow notification count endpoint to pass event types as a parameter

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PrisonerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/VisitorApprovedVisitNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitNotificationEventServiceTest.kt
When null comes back for some events, skip processing as it's not required. The null is because the prisonCode we have isn't active in our DB.
=> Change event processing to avoid NPE

helm_deploy/visit-scheduler/values.yaml
Update flagging visit number of days ahead param to 28 days.
Reporting improvements
=> Update flagging visit number of days ahead param to 28 days.

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/VisitPrivatePrisonClientReference.kt, src/main/resources/db/migration/V3_37__create_private_prison_client_id_reference_table.sql
Adds private prison client ref table
Enable associating a visit with a client reference
=> Added private prison client ref table and associated with visit table

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitStoreService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitStoreServiceTest.kt
This should fix an issue I spotted when trying to update visits from an external system. This is the error in the log:
```
ERROR: duplicate key value violates unique constraint "visit_notes_visit_id_type_key" Detail: Key (visit_id, type)=(1013, VISITOR_CONCERN) already exists.
```
I now force a `saveAndFlush` after clearing the visit notes and before adding the new visit notes that should mean that the table gets cleared before adding new ones, thus not triggering the unique contraint.
To fix issues with updating visits from external systems
=> Handle issues with updating visits from external systems due to uniqueness violations

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/VisitNotificationEventRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/CountVisitNotificationTest.kt
It's possible for a visit to have multiple events associated with it. This was causing the count to be higher than it technically was.
Changed to count visits, regardless of how many events are associated with visit.
https://dsdmoj.atlassian.net/browse/VB-3758
=> VB-3758 - Change count to count by visit, not by event type

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-staging.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/BookingRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/builder/VisitDtoBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/TelemetryClientService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitStoreService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookARequestedVisitFeatureDisabledTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/BookVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/CancelVisitTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitStoreServiceTest.kt, src/test/resources/application-test.yml
Allow booked visits to be request visits. If feature is enabled, check if isRequestVisit boolean is true, and set sub status to REQUESTED instead of AUTO_APPROVED.
Disabled by default until staff can handle requested visits.
https://dsdmoj.atlassian.net/browse/VB-5606
https://dsdmoj.atlassian.net/browse/VB-5679
https://dsdmoj.atlassian.net/browse/VB-5680
=> VB-5606 - Allow booked visits to be request visits

Dockerfile, build.gradle.kts, settings.gradle.kts
Remove the foojay resolver and change the Dockerfile image to use a JDK image, which allows us to build the code (compared to the JRE image being used which only run the code).
Also added to build gradle the JVM 21 version for the kotlin compile task to align with the version being used everywhere else.
=> Remove use of foojay resolver

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SnsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitRequestsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/ApproveVisitRequestTest.kt
Change name to be more descriptive, as it's only raised when a visit request is approved.
=> Change visit request approved event name to better reflect it's purpose

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/controller/VisitController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/VisitPreviewDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/audit/EventAuditDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/EventAudit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/PublicVisitService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitEventAuditService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/notify/NotifyCallbackNotificationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/notify/NotifyCreateNotificationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsByDateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/VisitsBySessionTemplateFilterTest.kt
Some of the collections within event audit and other sub visit entities were being eager loaded but not used by the frontend. Create a custom DTO which only captures the required fields and stop loading of lazy collections
=> Improve issue with endpoint eager loading collections for no reason

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/VisitRequestsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/NotificationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/visit/notifications/PrisonerReleasedVisitNotificationControllerTest.kt
VB-5940 - auto reject visits only when the released reason type is RELEASED
Fix for VB-5940 where requested visits are auto rejected when prisoner released to COURT
=> VB-5940 - auto reject visits only when the released reason type is RELEASED

src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/enums/SessionTemplateVisitOrderRestrictionType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/CreateSessionTemplateDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/SessionTemplateDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/dto/sessions/UpdateSessionTemplateDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/session/SessionTemplate.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/repository/SessionTemplateRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/service/SessionTemplateService.kt, src/main/resources/db/migration/V4_3__add_visit_order_restriction_enum_to_session_template.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityDataLoader.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/helper/EntityTestBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminCreateSessionsTemplateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminGetSessionTemplateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/integration/admin/AdminUpdateSessionTemplateTest.kt
There are 4 options (VO_PVO, VO, PVO, NONE). This will eventually be used to restrict sessions to prisoners who have the required VO type.
https://dsdmoj.atlassian.net/browse/VB-5800
https://dsdmoj.atlassian.net/browse/VB-5431
=> VB-5800 / VB-5431 - Allow session templates to set a visit order restriction
